spring.application.name=detection


spring.datasource.url=jdbc:postgresql://localhost:5432/mine_subsidence_db
spring.datasource.username=postgres
spring.datasource.password=Anish@2604
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

app.websocket.endpoint=/ws-telemetry

app.websocket.allowed-origins=*

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=50
spring.task.execution.pool.queue-capacity=1000
spring.task.execution.thread-name-prefix=Telemetry-Worker-